export default {
  // auth
  IS_LOADING: "IS_LOADING",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
  AUTENTICATED_SUCCESSFUL: "AUTENTICATED_SUCCESSFUL",
  //else
  SET_VALIDATION_ERROR: "SET_VALIDATION_ERROR",
  SET_NEW_EMPLOYEE_FORM_INPUT: "SET_NEW_EMPLOYEE_FORM_INPUT",
  SUBMIT_NEWEMPLOYEE_FORM: "SUBMIT_NEWEMPLOYEE_FORM",
  TRIM_INPUTS: "TRIM_INPUTS",
  ALL_INPUT_SET: "ALL_INPUT_SET",
  CLEAR_FORM_IMPUT: "CLEAR_FORM_IMPUT",
  ALL_EMPLOYEES: "ALL_EMPLOYEES",
  EACH_WORKER: "EACH_WORKER",
  DELETE_WORKER: "DELETE_WORKER",
  // upload fileStore
  BEFORE_UPLOAD: "BEFORE_UPLOAD",
  ON_SCAN_REMOVE: "ON_SCAN_REMOVE",
  SET_UPLOAD: "SET_UPLOAD",
  UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
  UPLOADING_FAILED: "UPLOADING_FAILED",
  CLEAR_FILELIST: "CLEAR_FILELIST",
  // docs
  UPDATE_SIGNED_DOCS: "UPDATE_SIGNED_DOCS",
  UPDATE_COLUMNS: "UPDATE_COLUMNS",
  // upload saga
  UPLOADS_SCANS_SC: "UPLOADS_SCANS_SC",
  UPLOADS_MEDS_SC: "UPLOADS_MEDS_SC",
  EDIT_EMPLOYEE_SC: "EDIT_EMPLOYEE_SC",
  SEED: "SEED",
  AUTH: "AUTH"
}
